import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    // "intro",
    // // {
    // //   type: 'category',
    // //   label: 'Tutorials',
    // //   items: ['tut-canned-responses'],
    // // },
    // {
    //   type: "category",
    //   label: "Recipes",
    //   link: {
    //     type: "doc",
    //     id: "recipes/index",
    //   },
    //   items: [
    //     "recipes/markdown-to-footnotes",
    //     "recipes/timezone-converter",
    //   ],
    // },
    {
      type: "category",
      label: "Reference",
      link: {
        type: "doc",
        id: "reference/index",
      },
      items: [
        "reference/macro-utility-library",
        "reference/markdown-directives",
        "reference/theme-bring-your-own",
        "reference/theme-example",
        "reference/theme-tailwind",
			  // "reference/snippet",
				// "reference/macro"
			],
    },
  ],
};

export default sidebars;
